RAND_KEY_SIZE = 1  # bytes
DATA_SIZE = 10  # bytes
OVERFLOW_PTR_SIZE = 4  # bytes
PAGE_KEY_SIZE = 4  # bytes

ALPHA = 0.5  # coef 0% - 100%
REORGANIZATION_TRESHOLD = 2.0  # coef 0% - inf

RECORDS_PER_CHUNK = 3
RECORD_SIZE = RAND_KEY_SIZE + DATA_SIZE + OVERFLOW_PTR_SIZE
CHUNK_SIZE = (RECORD_SIZE) * RECORDS_PER_CHUNK

INDEXES_PER_CHUNK = 5
INDEX_SIZE = RAND_KEY_SIZE + PAGE_KEY_SIZE
SPARSE_INDEX_CHUNK_SIZE = (RAND_KEY_SIZE + PAGE_KEY_SIZE) * INDEXES_PER_CHUNK
