RAND_KEY_SIZE = 4  # bytes
DATA_SIZE = 10  # bytes
OVERFLOW_PTR_SIZE = 4  # bytes

RECORD_SIZE = RAND_KEY_SIZE + DATA_SIZE + OVERFLOW_PTR_SIZE
RECORDS_PER_CHUNK = 20
CHUNK_SIZE = (RECORD_SIZE) * RECORDS_PER_CHUNK
